# Setting the prefix from C-b to C-a
set -g prefix C-a

# Free the original prefix binding
unbind C-b

# Setting the delay between prefix and command
set -s escape-time 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Reload config
bind r source-file ~/.tmux.conf \; display "~/.tmux.conf reloaded"

# Ensure that we can send C-a to applications
bind C-a send-prefix

# Quick window selection 
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Splitting panes with | and -
bind | split-window -h
bind - split-window -v

# Moving between panes with Prefix h, j, k, l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing panes with Prefix H, J, K, L
bind -r H resize-pane -L 5 
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Disable mouse support
set -g mouse off

# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# Set color for the active window
setw -g window-status-current-style fg=white,bold,bg=red

# Customize left status
set -g status-left-length 40
set -g status-left "[#S@#h]"

# Center window list
set -g status-justify centre

# Customize right status
set -g status-right "%R %d/%m/%y"

# Update the status line every 60 seconds
set -g status-interval 60

# Enable vi keys
setw -g mode-keys vi

# Enter copy-mode using Prefix Esc
bind Escape copy-mode

# vi copy key binding for tmux >2.3
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# vi paste key binding
unbind p
bind p paste-buffer

# shortcut for synchronize-pane toggle
bind C-s set-window-option synchronize-panes
